// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChatProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from ChatProtocol.proto</summary>
  public static partial class ChatProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for ChatProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJDaGF0UHJvdG9jb2wucHJvdG8SBXByb3RvImgKB0FuZ2FqYXQSDAoEbnVt",
            "ZRgBIAEoCRIPCgdwcmVudW1lGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJEhAK",
            "CHBhc3N3b3JkGAQgASgJEg4KBm9maWNpdRgFIAEoCRIKCgJpZBgGIAEoCSJp",
            "CgVCaWxldBIQCghpZF9iaWxldBgBIAEoAxISCgppZF9hbmdhamF0GAIgASgD",
            "EhEKCWlkX2NsaWVudBgDIAEoAxIUCgxpZF9zcGVjdGFjb2wYBCABKAMSEQoJ",
            "bnJfbG9jdXJpGAUgASgFImoKCVNwZWN0ZWNvbBIUCgxpZF9zcGVjdGFjb2wY",
            "ASABKAMSEQoJaWRfYXJ0aXN0GAIgASgDEg8KB2xvY2F0aWUYAyABKAkSEAoI",
            "ZGF0YV9pbmMYBCABKAkSEQoJbnJfbG9jdXJpGAUgASgFIhwKC0xpc3RhU3Ry",
            "aW5nEg0KBWxpc3RhGAEgAygJIiIKCE15c3RyaW5nEhYKDnVuX3Npbmd1cl9l",
            "bGVtGAEgASgJIiAKDUNoYXRFeGNlcHRpb24SDwoHbWVzc2FnZRgBIAEoCSLS",
            "AgoLRmVzdFJlcXVlc3QSJQoEdHlwZRgBIAEoDjIXLnByb3RvLkZlc3RSZXF1",
            "ZXN0LlR5cGUSHgoEdXNlchgCIAEoCzIOLnByb3RvLkFuZ2FqYXRIABIRCgdt",
            "ZXNzYWdlGAMgASgJSAAi3QEKBFR5cGUSIgoeRklORF9BUlRJU1RJX1NQRUNU",
            "QUNPTEVfQklMRVRFEAASLAooRklORF9BUlRJU1RJX1NQRUNUQUNPTEVfQklM",
            "RVRFX0RVUEFfREFUQRABEigKJEZJTkRfQVJUSVNUSV9TUEVDVEFDT0xFX0JJ",
            "TEVURV9JTkRFWBACEjIKLkZJTkRfQVJUSVNUSV9TUEVDVEFDT0xFX0JJTEVU",
            "RV9EVVBBX0RBVEFfSU5ERVgQAxIOCgpTQVZFX0JJTEVUEAQSCQoFVkFMSUQQ",
            "BRIKCgZMT0dPVVQQBkIJCgdwYXlsb2FkIvgBCgxGZXN0UmVzcG9uc2USJgoE",
            "dHlwZRgBIAEoDjIYLnByb3RvLkZlc3RSZXNwb25zZS5UeXBlEg0KBWVycm9y",
            "GAIgASgJEg0KBWxpc3RhGAMgAygJEhwKBHVzZXIYBCABKAsyDi5wcm90by5B",
            "bmdhamF0EiMKCXNwZWN0YWNvbBgFIAEoCzIQLnByb3RvLlNwZWN0ZWNvbBIb",
            "CgViaWxldBgGIAEoCzIMLnByb3RvLkJpbGV0EhYKDnVuX3Npbmd1cl9lbGVt",
            "GAcgASgJIioKBFR5cGUSBgoCT0sQABIJCgVFUlJPUhABEg8KC0JJTEVUX1NB",
            "VkVEEAJCNwoiZmVzdGl2YWwubmV0d29yay5wcm90b0J1ZmZQcm90b2NvbEIR",
            "RmVzdGl2YWxQcm90b2J1ZnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Angajat), global::Proto.Angajat.Parser, new[]{ "Nume", "Prenume", "Username", "Password", "Oficiu", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Bilet), global::Proto.Bilet.Parser, new[]{ "IdBilet", "IdAngajat", "IdClient", "IdSpectacol", "NrLocuri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Spectecol), global::Proto.Spectecol.Parser, new[]{ "IdSpectacol", "IdArtist", "Locatie", "DataInc", "NrLocuri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ListaString), global::Proto.ListaString.Parser, new[]{ "Lista" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Mystring), global::Proto.Mystring.Parser, new[]{ "UnSingurElem" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ChatException), global::Proto.ChatException.Parser, new[]{ "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.FestRequest), global::Proto.FestRequest.Parser, new[]{ "Type", "User", "Message" }, new[]{ "Payload" }, new[]{ typeof(global::Proto.FestRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.FestResponse), global::Proto.FestResponse.Parser, new[]{ "Type", "Error", "Lista", "User", "Spectacol", "Bilet", "UnSingurElem" }, null, new[]{ typeof(global::Proto.FestResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Angajat : pb::IMessage<Angajat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Angajat> _parser = new pb::MessageParser<Angajat>(() => new Angajat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Angajat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat(Angajat other) : this() {
      nume_ = other.nume_;
      prenume_ = other.prenume_;
      username_ = other.username_;
      password_ = other.password_;
      oficiu_ = other.oficiu_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat Clone() {
      return new Angajat(this);
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 1;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prenume" field.</summary>
    public const int PrenumeFieldNumber = 2;
    private string prenume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prenume {
      get { return prenume_; }
      set {
        prenume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 3;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 4;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oficiu" field.</summary>
    public const int OficiuFieldNumber = 5;
    private string oficiu_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Oficiu {
      get { return oficiu_; }
      set {
        oficiu_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 6;
    private string id_ = "";
    /// <summary>
    /// alte câmpuri specifice angajatului
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Angajat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Angajat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nume != other.Nume) return false;
      if (Prenume != other.Prenume) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (Oficiu != other.Oficiu) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Prenume.Length != 0) hash ^= Prenume.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Oficiu.Length != 0) hash ^= Oficiu.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Prenume);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Password);
      }
      if (Oficiu.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Oficiu);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Prenume);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Password);
      }
      if (Oficiu.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Oficiu);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Prenume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prenume);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Oficiu.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Oficiu);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Angajat other) {
      if (other == null) {
        return;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Prenume.Length != 0) {
        Prenume = other.Prenume;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Oficiu.Length != 0) {
        Oficiu = other.Oficiu;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 18: {
            Prenume = input.ReadString();
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Password = input.ReadString();
            break;
          }
          case 42: {
            Oficiu = input.ReadString();
            break;
          }
          case 50: {
            Id = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 18: {
            Prenume = input.ReadString();
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Password = input.ReadString();
            break;
          }
          case 42: {
            Oficiu = input.ReadString();
            break;
          }
          case 50: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Bilet : pb::IMessage<Bilet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet(Bilet other) : this() {
      idBilet_ = other.idBilet_;
      idAngajat_ = other.idAngajat_;
      idClient_ = other.idClient_;
      idSpectacol_ = other.idSpectacol_;
      nrLocuri_ = other.nrLocuri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet Clone() {
      return new Bilet(this);
    }

    /// <summary>Field number for the "id_bilet" field.</summary>
    public const int IdBiletFieldNumber = 1;
    private long idBilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdBilet {
      get { return idBilet_; }
      set {
        idBilet_ = value;
      }
    }

    /// <summary>Field number for the "id_angajat" field.</summary>
    public const int IdAngajatFieldNumber = 2;
    private long idAngajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdAngajat {
      get { return idAngajat_; }
      set {
        idAngajat_ = value;
      }
    }

    /// <summary>Field number for the "id_client" field.</summary>
    public const int IdClientFieldNumber = 3;
    private long idClient_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdClient {
      get { return idClient_; }
      set {
        idClient_ = value;
      }
    }

    /// <summary>Field number for the "id_spectacol" field.</summary>
    public const int IdSpectacolFieldNumber = 4;
    private long idSpectacol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdSpectacol {
      get { return idSpectacol_; }
      set {
        idSpectacol_ = value;
      }
    }

    /// <summary>Field number for the "nr_locuri" field.</summary>
    public const int NrLocuriFieldNumber = 5;
    private int nrLocuri_;
    /// <summary>
    /// alte câmpuri specifice biletului
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Bilet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Bilet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdBilet != other.IdBilet) return false;
      if (IdAngajat != other.IdAngajat) return false;
      if (IdClient != other.IdClient) return false;
      if (IdSpectacol != other.IdSpectacol) return false;
      if (NrLocuri != other.NrLocuri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdBilet != 0L) hash ^= IdBilet.GetHashCode();
      if (IdAngajat != 0L) hash ^= IdAngajat.GetHashCode();
      if (IdClient != 0L) hash ^= IdClient.GetHashCode();
      if (IdSpectacol != 0L) hash ^= IdSpectacol.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdBilet != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(IdBilet);
      }
      if (IdAngajat != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdAngajat);
      }
      if (IdClient != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(IdClient);
      }
      if (IdSpectacol != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(IdSpectacol);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdBilet != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(IdBilet);
      }
      if (IdAngajat != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdAngajat);
      }
      if (IdClient != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(IdClient);
      }
      if (IdSpectacol != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(IdSpectacol);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdBilet != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdBilet);
      }
      if (IdAngajat != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdAngajat);
      }
      if (IdClient != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdClient);
      }
      if (IdSpectacol != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdSpectacol);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Bilet other) {
      if (other == null) {
        return;
      }
      if (other.IdBilet != 0L) {
        IdBilet = other.IdBilet;
      }
      if (other.IdAngajat != 0L) {
        IdAngajat = other.IdAngajat;
      }
      if (other.IdClient != 0L) {
        IdClient = other.IdClient;
      }
      if (other.IdSpectacol != 0L) {
        IdSpectacol = other.IdSpectacol;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdBilet = input.ReadInt64();
            break;
          }
          case 16: {
            IdAngajat = input.ReadInt64();
            break;
          }
          case 24: {
            IdClient = input.ReadInt64();
            break;
          }
          case 32: {
            IdSpectacol = input.ReadInt64();
            break;
          }
          case 40: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdBilet = input.ReadInt64();
            break;
          }
          case 16: {
            IdAngajat = input.ReadInt64();
            break;
          }
          case 24: {
            IdClient = input.ReadInt64();
            break;
          }
          case 32: {
            IdSpectacol = input.ReadInt64();
            break;
          }
          case 40: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Spectecol : pb::IMessage<Spectecol>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Spectecol> _parser = new pb::MessageParser<Spectecol>(() => new Spectecol());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Spectecol> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectecol() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectecol(Spectecol other) : this() {
      idSpectacol_ = other.idSpectacol_;
      idArtist_ = other.idArtist_;
      locatie_ = other.locatie_;
      dataInc_ = other.dataInc_;
      nrLocuri_ = other.nrLocuri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectecol Clone() {
      return new Spectecol(this);
    }

    /// <summary>Field number for the "id_spectacol" field.</summary>
    public const int IdSpectacolFieldNumber = 1;
    private long idSpectacol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdSpectacol {
      get { return idSpectacol_; }
      set {
        idSpectacol_ = value;
      }
    }

    /// <summary>Field number for the "id_artist" field.</summary>
    public const int IdArtistFieldNumber = 2;
    private long idArtist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdArtist {
      get { return idArtist_; }
      set {
        idArtist_ = value;
      }
    }

    /// <summary>Field number for the "locatie" field.</summary>
    public const int LocatieFieldNumber = 3;
    private string locatie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Locatie {
      get { return locatie_; }
      set {
        locatie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data_inc" field.</summary>
    public const int DataIncFieldNumber = 4;
    private string dataInc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DataInc {
      get { return dataInc_; }
      set {
        dataInc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nr_locuri" field.</summary>
    public const int NrLocuriFieldNumber = 5;
    private int nrLocuri_;
    /// <summary>
    /// alte câmpuri specifice spectacolului
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Spectecol);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Spectecol other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdSpectacol != other.IdSpectacol) return false;
      if (IdArtist != other.IdArtist) return false;
      if (Locatie != other.Locatie) return false;
      if (DataInc != other.DataInc) return false;
      if (NrLocuri != other.NrLocuri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdSpectacol != 0L) hash ^= IdSpectacol.GetHashCode();
      if (IdArtist != 0L) hash ^= IdArtist.GetHashCode();
      if (Locatie.Length != 0) hash ^= Locatie.GetHashCode();
      if (DataInc.Length != 0) hash ^= DataInc.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdSpectacol != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(IdSpectacol);
      }
      if (IdArtist != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdArtist);
      }
      if (Locatie.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Locatie);
      }
      if (DataInc.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DataInc);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdSpectacol != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(IdSpectacol);
      }
      if (IdArtist != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdArtist);
      }
      if (Locatie.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Locatie);
      }
      if (DataInc.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DataInc);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdSpectacol != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdSpectacol);
      }
      if (IdArtist != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdArtist);
      }
      if (Locatie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Locatie);
      }
      if (DataInc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataInc);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Spectecol other) {
      if (other == null) {
        return;
      }
      if (other.IdSpectacol != 0L) {
        IdSpectacol = other.IdSpectacol;
      }
      if (other.IdArtist != 0L) {
        IdArtist = other.IdArtist;
      }
      if (other.Locatie.Length != 0) {
        Locatie = other.Locatie;
      }
      if (other.DataInc.Length != 0) {
        DataInc = other.DataInc;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdSpectacol = input.ReadInt64();
            break;
          }
          case 16: {
            IdArtist = input.ReadInt64();
            break;
          }
          case 26: {
            Locatie = input.ReadString();
            break;
          }
          case 34: {
            DataInc = input.ReadString();
            break;
          }
          case 40: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdSpectacol = input.ReadInt64();
            break;
          }
          case 16: {
            IdArtist = input.ReadInt64();
            break;
          }
          case 26: {
            Locatie = input.ReadString();
            break;
          }
          case 34: {
            DataInc = input.ReadString();
            break;
          }
          case 40: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ListaString : pb::IMessage<ListaString>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ListaString> _parser = new pb::MessageParser<ListaString>(() => new ListaString());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ListaString> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListaString() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListaString(ListaString other) : this() {
      lista_ = other.lista_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListaString Clone() {
      return new ListaString(this);
    }

    /// <summary>Field number for the "lista" field.</summary>
    public const int ListaFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_lista_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> lista_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// alte câmpuri specifice, dacă este necesar
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Lista {
      get { return lista_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ListaString);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ListaString other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!lista_.Equals(other.lista_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= lista_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      lista_.WriteTo(output, _repeated_lista_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      lista_.WriteTo(ref output, _repeated_lista_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += lista_.CalculateSize(_repeated_lista_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ListaString other) {
      if (other == null) {
        return;
      }
      lista_.Add(other.lista_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            lista_.AddEntriesFrom(input, _repeated_lista_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            lista_.AddEntriesFrom(ref input, _repeated_lista_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Mystring : pb::IMessage<Mystring>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Mystring> _parser = new pb::MessageParser<Mystring>(() => new Mystring());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Mystring> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Mystring() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Mystring(Mystring other) : this() {
      unSingurElem_ = other.unSingurElem_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Mystring Clone() {
      return new Mystring(this);
    }

    /// <summary>Field number for the "un_singur_elem" field.</summary>
    public const int UnSingurElemFieldNumber = 1;
    private string unSingurElem_ = "";
    /// <summary>
    /// alte câmpuri specifice, dacă este necesar
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UnSingurElem {
      get { return unSingurElem_; }
      set {
        unSingurElem_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Mystring);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Mystring other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnSingurElem != other.UnSingurElem) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UnSingurElem.Length != 0) hash ^= UnSingurElem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UnSingurElem.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UnSingurElem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UnSingurElem.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UnSingurElem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UnSingurElem.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UnSingurElem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Mystring other) {
      if (other == null) {
        return;
      }
      if (other.UnSingurElem.Length != 0) {
        UnSingurElem = other.UnSingurElem;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UnSingurElem = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UnSingurElem = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChatException : pb::IMessage<ChatException>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatException> _parser = new pb::MessageParser<ChatException>(() => new ChatException());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatException> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatException() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatException(ChatException other) : this() {
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatException Clone() {
      return new ChatException(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    /// <summary>
    /// alte câmpuri specifice excepției
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatException);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatException other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatException other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FestRequest : pb::IMessage<FestRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FestRequest> _parser = new pb::MessageParser<FestRequest>(() => new FestRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FestRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FestRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FestRequest(FestRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          User = other.User.Clone();
          break;
        case PayloadOneofCase.Message:
          Message = other.Message;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FestRequest Clone() {
      return new FestRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.FestRequest.Types.Type type_ = global::Proto.FestRequest.Types.Type.FindArtistiSpectacoleBilete;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.FestRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Angajat User {
      get { return payloadCase_ == PayloadOneofCase.User ? (global::Proto.Angajat) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.User;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return HasMessage ? (string) payload_ : ""; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.Message;
      }
    }
    /// <summary>Gets whether the "message" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMessage {
      get { return payloadCase_ == PayloadOneofCase.Message; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "message" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      if (HasMessage) {
        ClearPayload();
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      User = 2,
      Message = 3,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FestRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FestRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (Message != other.Message) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.FestRequest.Types.Type.FindArtistiSpectacoleBilete) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.User) hash ^= User.GetHashCode();
      if (HasMessage) hash ^= Message.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.FestRequest.Types.Type.FindArtistiSpectacoleBilete) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (HasMessage) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.FestRequest.Types.Type.FindArtistiSpectacoleBilete) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (HasMessage) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.FestRequest.Types.Type.FindArtistiSpectacoleBilete) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (HasMessage) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FestRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.FestRequest.Types.Type.FindArtistiSpectacoleBilete) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          if (User == null) {
            User = new global::Proto.Angajat();
          }
          User.MergeFrom(other.User);
          break;
        case PayloadOneofCase.Message:
          Message = other.Message;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.FestRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Angajat subBuilder = new global::Proto.Angajat();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.FestRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Angajat subBuilder = new global::Proto.Angajat();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the FestRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("FIND_ARTISTI_SPECTACOLE_BILETE")] FindArtistiSpectacoleBilete = 0,
        [pbr::OriginalName("FIND_ARTISTI_SPECTACOLE_BILETE_DUPA_DATA")] FindArtistiSpectacoleBileteDupaData = 1,
        [pbr::OriginalName("FIND_ARTISTI_SPECTACOLE_BILETE_INDEX")] FindArtistiSpectacoleBileteIndex = 2,
        [pbr::OriginalName("FIND_ARTISTI_SPECTACOLE_BILETE_DUPA_DATA_INDEX")] FindArtistiSpectacoleBileteDupaDataIndex = 3,
        /// <summary>
        ///  SAVE_PERSOANA_RETURN_ID_PERS = 4;
        ///  SAVE_CLIENT_RETURN_ID_CLIENT = 5;
        /// </summary>
        [pbr::OriginalName("SAVE_BILET")] SaveBilet = 4,
        [pbr::OriginalName("VALID")] Valid = 5,
        [pbr::OriginalName("LOGOUT")] Logout = 6,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FestResponse : pb::IMessage<FestResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FestResponse> _parser = new pb::MessageParser<FestResponse>(() => new FestResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FestResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ChatProtocolReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FestResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FestResponse(FestResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      lista_ = other.lista_.Clone();
      user_ = other.user_ != null ? other.user_.Clone() : null;
      spectacol_ = other.spectacol_ != null ? other.spectacol_.Clone() : null;
      bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
      unSingurElem_ = other.unSingurElem_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FestResponse Clone() {
      return new FestResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.FestResponse.Types.Type type_ = global::Proto.FestResponse.Types.Type.Ok;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.FestResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lista" field.</summary>
    public const int ListaFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_lista_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> lista_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Lista {
      get { return lista_; }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 4;
    private global::Proto.Angajat user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Angajat User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "spectacol" field.</summary>
    public const int SpectacolFieldNumber = 5;
    private global::Proto.Spectecol spectacol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Spectecol Spectacol {
      get { return spectacol_; }
      set {
        spectacol_ = value;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 6;
    private global::Proto.Bilet bilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Bilet Bilet {
      get { return bilet_; }
      set {
        bilet_ = value;
      }
    }

    /// <summary>Field number for the "un_singur_elem" field.</summary>
    public const int UnSingurElemFieldNumber = 7;
    private string unSingurElem_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UnSingurElem {
      get { return unSingurElem_; }
      set {
        unSingurElem_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FestResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FestResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!lista_.Equals(other.lista_)) return false;
      if (!object.Equals(User, other.User)) return false;
      if (!object.Equals(Spectacol, other.Spectacol)) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (UnSingurElem != other.UnSingurElem) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.FestResponse.Types.Type.Ok) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= lista_.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (spectacol_ != null) hash ^= Spectacol.GetHashCode();
      if (bilet_ != null) hash ^= Bilet.GetHashCode();
      if (UnSingurElem.Length != 0) hash ^= UnSingurElem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.FestResponse.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      lista_.WriteTo(output, _repeated_lista_codec);
      if (user_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(User);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Spectacol);
      }
      if (bilet_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Bilet);
      }
      if (UnSingurElem.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(UnSingurElem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.FestResponse.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      lista_.WriteTo(ref output, _repeated_lista_codec);
      if (user_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(User);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Spectacol);
      }
      if (bilet_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Bilet);
      }
      if (UnSingurElem.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(UnSingurElem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.FestResponse.Types.Type.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += lista_.CalculateSize(_repeated_lista_codec);
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (spectacol_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
      }
      if (bilet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (UnSingurElem.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UnSingurElem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FestResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.FestResponse.Types.Type.Ok) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      lista_.Add(other.lista_);
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Proto.Angajat();
        }
        User.MergeFrom(other.User);
      }
      if (other.spectacol_ != null) {
        if (spectacol_ == null) {
          Spectacol = new global::Proto.Spectecol();
        }
        Spectacol.MergeFrom(other.Spectacol);
      }
      if (other.bilet_ != null) {
        if (bilet_ == null) {
          Bilet = new global::Proto.Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
      }
      if (other.UnSingurElem.Length != 0) {
        UnSingurElem = other.UnSingurElem;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.FestResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            lista_.AddEntriesFrom(input, _repeated_lista_codec);
            break;
          }
          case 34: {
            if (user_ == null) {
              User = new global::Proto.Angajat();
            }
            input.ReadMessage(User);
            break;
          }
          case 42: {
            if (spectacol_ == null) {
              Spectacol = new global::Proto.Spectecol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
          case 50: {
            if (bilet_ == null) {
              Bilet = new global::Proto.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 58: {
            UnSingurElem = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.FestResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            lista_.AddEntriesFrom(ref input, _repeated_lista_codec);
            break;
          }
          case 34: {
            if (user_ == null) {
              User = new global::Proto.Angajat();
            }
            input.ReadMessage(User);
            break;
          }
          case 42: {
            if (spectacol_ == null) {
              Spectacol = new global::Proto.Spectecol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
          case 50: {
            if (bilet_ == null) {
              Bilet = new global::Proto.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 58: {
            UnSingurElem = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the FestResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("BILET_SAVED")] BiletSaved = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
