package festival.network.rpcprotocol;


public enum RequestType {
    FIND_ARTISTI_SPECTACOLE_BILETE,
    FIND_ARTISTI_SPECTACOLE_BILETE_DUPA_DATA,
    FIND_ARTISTI_SPECTACOLE_BILETE_INDEX,
    FIND_ARTISTI_SPECTACOLE_BILETE_DUPA_DATA_INDEX,
//    SAVE_PERSOANA_RETURN_ID_PERS,
//    SAVE_CLIENT_RETURN_ID_CLIENT,
    SAVE_BILET,
    VALID, LOGOUT;
}
